apiVersion: constraints.gatekeeper.sh/v1beta1
kind: PrivilegedContainerConstraint
metadata:
  name: privileged-container-constraint
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces: ["kube-system"]
